const namespace = "BOTTOMSHEET_";

const CONSTANTS = {
  BOTTOMSHEET_SHARE_CONTENT_VIA: `${namespace}SHARE_CONTENT_VIA`,
  BOTTOMSHEET_ABOUT_THIS_COURSE: `${namespace}ABOUT_THIS_COURSE`,
  BOTTOMSHEET_VIDEO_RESTRICTIONS: `${namespace}VIDEO_RESTRICTIONS`,
  BOTTOMSHEET_UPCOMING_LIVE_CLASSES: `${namespace}UPCOMING_LIVE_CLASSES`,
  BOTTOMSHEET_APPLY_COUPON: `${namespace}APPLY_COUPON`,
  BOTTOMSHEET_CONTENT_LOCKED: `${namespace}CONTENT_LOCKED`,
  BOTTOMSHEET_WHAT_ARE_YOU_WATCHING: `${namespace}WHAT_ARE_YOU_WATCHING`,
  BOTTOMSHEET_TEST_IS_LOCKED: `${namespace}TEST_IS_LOCKED`,
  BOTTOMSHEET_SELECT_STATE: `${namespace}SELECT_STATE`,
  BOTTOMSHEET_SELECT_ADDRESS: `${namespace}SELECT_ADDRESS`,
  POPUP_DELETE_ADDRESS: `${namespace}DELETE_ADDRESS`,

  BOTTOMSHEET_RUNNING_TIGHT_ON_BUDGET: `${namespace}RUNNING_TIGHT_ON_BUDGET`,
  BOTTOMSHEET_CONGRATULATIONS: `${namespace}CONGRATULATIONS`,
  BOTTOMSHEET_DUE_DATE: `${namespace}DUE_DATE`,
  BOTTOMSHEET_COURSE_LOCKED: `${namespace}COURSE_LOCKED`,
  BOTTOMSHEET_PAYMENT_FAILED: `${namespace}PAYMENT_FAILED`,

  BOTTOMSHEET_VIEWS_EXHAUSTED: `${namespace}VIEWS_EXHAUSTED`,
  BOTTOMSHEET_DOWNLOAD_VIDEO: `${namespace}DOWNLOAD_VIDEO`,
  BOTTOMSHEET_EXPIRY_SOON: `${namespace}EXPIRY_SOON`,
  BOTTOMSHEET_PAYMENT_PROCESSING: `${namespace}PAYMENT_PROCESSING`,

  BOTTOMSHEET_TEST_IS_TEMPORARILY_LOCKED: `${namespace}TEST_IS_TEMPORARILY_LOCKED`,
  BOTTOMSHEET_TEST_IS_TEMPORARILY_LOCKED_TIMING: `${namespace}TEST_IS_TEMPORARILY_LOCKED_TIMING`,
  BOTTOMSHEET_ANNOUNCEMENTS_ATTACHMENTS: `${namespace}ANNOUNCEMENTS_ATTACHMENTS`,

  BOTTOMSHEET_IS_SHOW_TIGHT_ON_BUDGET: `${namespace}IS_SHOW_TIGHT_ON_BUDGET`,

  CLOSE_ALL_BOTTOMSHEET: `CLOSE_ALL_${namespace}`,
  SHOW_FULLSCREEN_LOADER: `SHOW_FULLSCREEN_LOADER`,
  SHOW_PAYMENT_LOADER: `SHOW_PAYMENT_LOADER`,
};

export default CONSTANTS;
