// ENUMS FOR CONTENT TYPES
export const CONTENT_TYPE = {
  FOLDER: 1,
  VIDEO: 2,
  DOCUMENT: 3,
  TEST: 4,
  // ONLY 4 CONTENT_TYPES ARE AT BACKEND, REST ARE FOR FRONTENT
  LIVE_CLASS: 5,
  ZIP: 6,
  SUBJECTIVE_TEST: 7,
  IMAGE: 8,
};

// LIMIT TO FETCH NUMBER OF CONTENT ITEMS AT A TIME
export const CONTENT_LIMIT = 10;

// CONTENT DOWNLOAD STATUS CODES
export const CONTENT_DOWNLOAD_STATUS = {
  DOWNLOAD_START: 0,
  DOWNLOAD_IN_PROGRESS: 1,
  DOWNLOAD_PAUSE: 2,
  DOWNLOAD_RESUME: 3,
  DOWNLOAD_FAILED: 4,
  DOWNLOAD_SUCCESS: 5,
  DOWNLOAD_REMOVE: 6,
  DOWNLOAD_CANCEL: 7,
  DOWNLOAD_QUEUED: 8,
  DOWNLOAD_ALREADY_DOWNLOADED: 9,
  DOWNLOAD_UNKNOWN: 10,
  DOWNLOAD_ALREADY_IN_PROGRESS: 11,
};

// DEEPLINK ACTION CONSTANTS
const deeplinkNamespace = "ACTION";

export const CONTENT_DEEPLINK_ACTIONS = {
  // OLD DEEPLINK ACTION TO VIEW IMAGE/PDF
  SCREEN_CONTENT: `SCREEN_CONTENT`,
  UTIL_TEST: `UTIL_TEST`,

  // OPEN CONTENT ITEM DEEPLINK ACTIONS
  ACTION_PLAY_VIDEO: `${deeplinkNamespace}_PLAY_VIDEO`,
  ACTION_OPEN_PDF: `${deeplinkNamespace}_OPEN_PDF`,
  ACTION_OPEN_IMAGE: `${deeplinkNamespace}_OPEN_IMAGE`,

  // DOWNLOAD CONTENT ITEM DEEPLINK ACTIONS
  ACTION_DOWNLOAD_FILE: `${deeplinkNamespace}_DOWNLOAD_FILE`, // NEED STORAGE PERMISSSION
  ACTION_DOWNLOAD_VIDEO_OFFLINE: `${deeplinkNamespace}_DOWNLOAD_VIDEO_OFFLINE`, // NEED STORAGE PERMISSSION
  ACTION_REMOVE_VIDEO_OFFLINE: `${deeplinkNamespace}_REMOVE_VIDEO_OFFLINE`,

  // TEST ATTEMPT WEBVIEW DEEPLINK ACTIONS
  ACTION_TEST_ATTEMPT: `${deeplinkNamespace}_TEST_ATTEMPT`, // NEED STORAGE PERMISSSION
  ACTION_TEST_REATTEMPT: `${deeplinkNamespace}_TEST_REATTEMPT`, // NEED STORAGE PERMISSSION

  // STORAGE PERMISSION DEEPLINK ACTIONS
  ACTION_CHECK_STORAGE_PERMISSION: `${deeplinkNamespace}_CHECK_STORAGE_PERMISSION`,
  ACTION_REQUEST_STORAGE_PERMISSION: `${deeplinkNamespace}_REQUEST_STORAGE_PERMISSION`,

  // GET OFFLINE DOWNLOADED ITEMS LIST DEEPLINK ACTION
  ACTION_GET_OFFLINE_DOWNLOAD_LIST: `${deeplinkNamespace}_GET_OFFLINE_DOWNLOAD_LIST`,
};

// REDUX CONSTANTS
const namespace = "COURSE_CONTENT";

const CONSTANTS = {
  LOCKED_COURSE_CONTENT: `LOCKED_${namespace}`,
  EXHAUSTED_COUNT_COURSE_CONTENT: `EXHAUSTED_COUNT_${namespace}`,

  ACTIVE_COURSE_CONTENT_FOLDER_ID: `ACTIVE_${namespace}_FOLDER_ID`,

  CLEAR_FREE_COURSE_CONTENT: `CLEAR_FREE_${namespace}`,
  GET_FREE_COURSE_CONTENT: `GET_FREE_${namespace}`,
  GET_FREE_COURSE_CONTENT_LOADER: `GET_FREE_${namespace}_LOADER`,
  GET_FREE_COURSE_CONTENT_SUCCESS: `GET_FREE_${namespace}_SUCCESS`,
  GET_FREE_COURSE_CONTENT_FAILURE: `GET_FREE_${namespace}_FAILURE`,

  GET_FREE_COURSE_CONTENT_LOAD_MORE: `GET_FREE_${namespace}_LOAD_MORE`,
  GET_FREE_COURSE_CONTENT_LOADED_MORE: `GET_FREE_${namespace}_LOADED_MORE`,

  CLEAR_COURSE_CONTENT: `CLEAR_${namespace}`,
  GET_COURSE_CONTENT: `GET_${namespace}`,
  GET_COURSE_CONTENT_LOADER: `GET_${namespace}_LOADER`,
  GET_COURSE_CONTENT_SUCCESS: `GET_${namespace}_SUCCESS`,
  GET_COURSE_CONTENT_FAILURE: `GET_${namespace}_FAILURE`,

  GET_COURSE_CONTENT_LOAD_MORE: `GET_${namespace}_LOAD_MORE`,
  GET_COURSE_CONTENT_LOADED_MORE: `GET_${namespace}_LOADED_MORE`,

  CLEAR_COURSE_CONTENT_TEST_STATS: `CLEAR_${namespace}_TEST_STATS`,
  GET_COURSE_CONTENT_TEST_STATS: `GET_${namespace}_TEST_STATS`,
  GET_COURSE_CONTENT_TEST_STATS_LOADER: `GET_${namespace}_TEST_STATS_LOADER`,
  GET_COURSE_CONTENT_TEST_STATS_SUCCESS: `GET_${namespace}_TEST_STATS_SUCCESS`,
  GET_COURSE_CONTENT_TEST_STATS_FAILURE: `GET_${namespace}_TEST_STATS_FAILURE`,

  CLEAR_PREVIEW_VIDEO_CONTENT: `CLEAR_PREVIEW_VIDEO_CONTENT`,
  ADD_PREVIEW_VIDEO_CONTENT: `CLEAR_PREVIEW_VIDEO_CONTENT`,
  ADD_PREVIEW_VIDEO_CONTENT_LOADER: `CLEAR_PREVIEW_VIDEO_CONTENT_LOADER`,
  ADD_PREVIEW_VIDEO_CONTENT_SUCCESS: `CLEAR_PREVIEW_VIDEO_CONTENT_SUCCESS`,
  ADD_PREVIEW_VIDEO_CONTENT_FAILURE: `CLEAR_PREVIEW_VIDEO_CONTENT_FAILURE`,
};

export default CONSTANTS;
