const namespace = "COURSE_PAYMENT";

export const CONSTANTS = {
  CREATE_ORDER: `${namespace}_CREATE_ORDER`,
  PAYMENT_CHECKOUT: `${namespace}_PAYMENT_CHECKOUT`,
  CHECK_PAYMENT_STATUS: `${namespace}_CHECK_PAYMENT_STATUS`,
  CREATE_ORDER_POST: `${namespace}_CREATE_ORDER_POST`,
  PAYMENT_CHECKOUT_GET: `${namespace}_PAYMENT_CHECKOUT_GET`,
  CHECK_PAYMENT_STATUS_GET: `${namespace}_CHECK_PAYMENT_STATUS_GET`,
};
