const namespace = "COURSEGOLIVE_";

const CONSTANTS = {
  GOLIVE_DATA_GET: `${namespace}DATA_GET`,
  GOLIVE_DATA_LOADING: `${namespace}DATA_LOADING`,
  GOLIVE_DATA_SUCCESS: `${namespace}DATA_SUCCESS`,
  GOLIVE_DATA_ERROR: `${namespace}DATA_ERROR`,

  GOLIVE_SESSION_POST: `${namespace}SESSION_POST`,
  GOLIVE_SESSION_LOADING: `${namespace}SESSION_LOADING`,
  GOLIVE_SESSION_SUCCESS: `${namespace}SESSION_SUCCESS`,
  GOLIVE_SESSION_ERROR: `${namespace}SESSION_ERROR`,

  GOLIVE_SESSIONUPDATE_UPDATE: `${namespace}SESSIONUPDATE_UPDATE`,
  GOLIVE_SESSIONUPDATE_LOADING: `${namespace}SESSIONUPDATE_LOADING`,
  GOLIVE_SESSIONUPDATE_SUCCESS: `${namespace}SESSIONUPDATE_SUCCESS`,
  GOLIVE_SESSIONUPDATE_ERROR: `${namespace}SESSIONUPDATE_ERROR`,

  GOLIVE_SESSIONDELETE_DELETE: `${namespace}SESSIONUPDATE_DELETE`,
  GOLIVE_SESSIONDELETE_LOADING: `${namespace}SESSIONUPDATE_LOADING`,
  GOLIVE_SESSIONDELETE_SUCCESS: `${namespace}SESSIONUPDATE_SUCCESS`,
  GOLIVE_SESSIONDELETE_ERROR: `${namespace}SESSIONUPDATE_ERROR`,

  GOLIVE_REDIRECT: `${namespace}REDIRECT`,
};

export default CONSTANTS;
