// COURSE TAB ENUMS
export const COURSE_TABS_ENUMS = {
  OVERVIEW: "overview",
  CONTENT: "content",
  LIVECLASS: "liveClasses",
  ANNOUNCEMENTS: "announcements",
};

// DEEPLINK ACTION ENUMS
const deeplinkNamespace = "ACTION";
export const DEEPLINK_ACTIONS = {
  ACTION_GET_REFRESH_TOKEN: `${deeplinkNamespace}_GET_REFRESH_TOKEN`,
};

// OFFLINE DOWNLOAD STATE ENUMS
// export const DOWNLOAD_STATES = {
//   DOWNLOAD_START: 0,
//   DOWNLOAD_IN_PROGRESS: 1,
//   DOWNLOAD_PAUSE: 2,
//   DOWNLOAD_RESUME: 3,
//   DOWNLOAD_FAILED: 4,
//   DOWNLOAD_SUCCESS: 5,
//   DOWNLOAD_REMOVE: 6,
//   DOWNLOAD_CANCEL: 7,
//   DOWNLOAD_QUEUED: 8,
//   FILE_ALREADY_DOWNLOADED: 9,
//   DOWNLOAD_UNKNOWN: 10,
//   DOWNLOAD_ALREADY_IN_PROGRESS: 11,
// };
